spring.application.name=IntroThymeleaf

server.port=8082

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que Hibernate cree y actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Opcional: Activa la consola web de H2 para ver tus tablas en el navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
